version: '3.3'
services:
    pocketbase:
        ports:
            - '8090:8090'
        environment:
            - 'R2_BUCKET=${R2_BUCKET}'
            - 'R2_ACCESS_KEY=${R2_ACCESS_KEY}'
            - 'R2_SECRET_KEY=${R2_SECRET_KEY}'
            - 'R2_DATA_PATH=${R2_DATA_PATH}'
            - 'R2_LOGS_PATH=${R2_LOGS_PATH}'
            - 'R2_URL=${R2_URL}'
        # image: 'pocketbase:latest'
        build: .